### ISSUE TITLE
control transfer/系统相关结构完善(中断，交换内存，指令环...)

### ISSUE THREAD

**Issue by ZR233** [dbydd/arceos_experiment#9]
先实现最基本的传输

**Comment by xxczxp** [comment]
遇到bug：
```
[  1.439813 0 driver_usb::host::xhci:44] init statics
[  1.440651 0 driver_usb::host::xhci:52] get bios perms
[  1.441411 0 driver_usb::host::xhci:69] stop
[  1.442084 0 driver_usb::host::xhci:76] wait until halt
[  1.442886 0 driver_usb::host::xhci:81] start reset
[  1.443644 0 driver_usb::host::xhci:88] wait until reset complete
[  1.444554 0 driver_usb::host::xhci:93] wait until ready
[  1.445367 0 driver_usb::host::xhci:103] setting num of slots:32
[  1.446337 0 driver_usb::host::xhci:115] run!
[  1.446961 0 driver_usb::host::xhci:127] s is UsbStatusRegister { hc_halted: true, host_system_error: true, event_interrupt: false, port_change_detect: true, save_state_status: false, restore_state_status: false, save_restore_error: false, controller_not_ready: false, host_controller_error: false }
[  1.450404 0 driver_usb::host::xhci:128] UsbCommandRegister { run_stop: false, host_controller_reset: false, interrupter_enable: false, host_system_error_enable: false, light_host_controller_reset: false, controller_save_state: false, controller_restore_state: false, enable_wrap_event: false, enable_u3_mfindex_stop: false, cem_enable: false, extended_tbc_enable: false, extended_tbc_trb_status_enable: false, vtio_enable: false }
[  1.455250 0 axruntime::lang_items:5] panicked at crates/driver_usb/src/host/xhci/mod.rs:129:9:
HC is halted.
[  1.456648 0 axhal::platform::aarch64_raspi::misc:21] Shutting down...
```

在xHCI启动后却意外停止了，主要的错误报告是`host_system_error: true`
在手册中查找：
Host System Error (HSE) – RW1C. Default = ‘0’. The xHC sets this bit to ‘1’ when a serious error 
is detected, either internal to the xHC or during a host system access involving the xHC module. 
(In a PCI system, conditions that set this bit to ‘1’ include PCI Parity error, PCI Master Abort, and 
PCI Target Abort.) When this error occurs, the xHC clears the Run/Stop (R/S) bit in the USBCMD 
register to prevent further execution of the scheduled TDs. If the HSEE bit in the USBCMD 
register is a ‘1’, the xHC shall also assert out-of-band error signaling to the host. Refer to section 
4.10.2.6 for more information.
When this register is exposed by a Virtual Function (VF), the assertion of this bit affects all VFs 
and reflects the Host System Error state of the Physical Function (PF0). Refer to section 8 for 
more information.

**Comment by dbydd** [comment]
> 遇到bug：
> 
> ```
> [  1.439813 0 driver_usb::host::xhci:44] init statics
> [  1.440651 0 driver_usb::host::xhci:52] get bios perms
> [  1.441411 0 driver_usb::host::xhci:69] stop
> [  1.442084 0 driver_usb::host::xhci:76] wait until halt
> [  1.442886 0 driver_usb::host::xhci:81] start reset
> [  1.443644 0 driver_usb::host::xhci:88] wait until reset complete
> [  1.444554 0 driver_usb::host::xhci:93] wait until ready
> [  1.445367 0 driver_usb::host::xhci:103] setting num of slots:32
> [  1.446337 0 driver_usb::host::xhci:115] run!
> [  1.446961 0 driver_usb::host::xhci:127] s is UsbStatusRegister { hc_halted: true, host_system_error: true, event_interrupt: false, port_change_detect: true, save_state_status: false, restore_state_status: false, save_restore_error: false, controller_not_ready: false, host_controller_error: false }
> [  1.450404 0 driver_usb::host::xhci:128] UsbCommandRegister { run_stop: false, host_controller_reset: false, interrupter_enable: false, host_system_error_enable: false, light_host_controller_reset: false, controller_save_state: false, controller_restore_state: false, enable_wrap_event: false, enable_u3_mfindex_stop: false, cem_enable: false, extended_tbc_enable: false, extended_tbc_trb_status_enable: false, vtio_enable: false }
> [  1.455250 0 axruntime::lang_items:5] panicked at crates/driver_usb/src/host/xhci/mod.rs:129:9:
> HC is halted.
> [  1.456648 0 axhal::platform::aarch64_raspi::misc:21] Shutting down...
> ```
> 
> 在xHCI启动后却意外停止了，主要的错误报告是`host_system_error: true` 在手册中查找： Host System Error (HSE) – RW1C. Default = ‘0’. The xHC sets this bit to ‘1’ when a serious error is detected, either internal to the xHC or during a host system access involving the xHC module. (In a PCI system, conditions that set this bit to ‘1’ include PCI Parity error, PCI Master Abort, and PCI Target Abort.) When this error occurs, the xHC clears the Run/Stop (R/S) bit in the USBCMD register to prevent further execution of the scheduled TDs. If the HSEE bit in the USBCMD register is a ‘1’, the xHC shall also assert out-of-band error signaling to the host. Refer to section 4.10.2.6 for more information. When this register is exposed by a Virtual Function (VF), the assertion of this bit affects all VFs and reflects the Host System Error state of the Physical Function (PF0). Refer to section 8 for more information.
=======================================================================================

多试了几次，非常怪，3/10的可能跑起来，5/10的可能挂在wait上面，2/10的可能前面的wait过了，但是后面的检查又panic了
总感觉可能是内存同步问题依然没有完全修好(

![Image](https://github.com/arceos-usb/arceos_experiment/assets/44134872/ec22f2fa-d096-4953-887e-3debb78264e0)

另外，我们还得把multitask/executer这个任务执行器启动起来，或者arceos本身有多线程执行器嘛？适配一下？

**Comment by xxczxp** [comment]
那个内存同步要不开一个待办？最开始的那个bug，感觉解决方法很玄学

**Comment by dbydd** [comment]
那就开呗，我拉你进组（

**Comment by ZR233** [comment]
用最新的next分支测试了吗？我这没出现过error的情况呢

**Comment by dbydd** [comment]
> 用最新的next分支测试了吗？我这没出现过error的情况呢

我开分支的时候用的就是next分支，最新的(

**Comment by dbydd** [comment]
玄学问题就先玄学对待罢，还是有几次能正常开起来的，多开开就行，之后再排查（
usb驱动需要多线程，正在进行多线程相关的代码适配，工作量比较小，明天直接干掉后应该或许大概就能开始写具体的驱动了，也许后续可以改成协程？

**Comment by xxczxp** [comment]
> 玄学问题就先玄学对待罢，还是有几次能正常开起来的，多开开就行，之后再排查（ usb驱动需要多线程，正在进行多线程相关的代码适配，工作量比较小，明天直接干掉后应该或许大概就能开始写具体的驱动了，也许后续可以改成协程？

rust好像没有官方协程，只有await async模型，代码中executer应该就是基于await async模型实现的。又或者说把整个程序都扔到一个executer里来提高性能？
话说还有什么代码需要写的？

**Comment by ZR233** [comment]
其实先按单usb设备来搞可以暂时不需要多线程，建议能简化就简化，先把整个流程跑通

**Comment by dbydd** [comment]
> > 玄学问题就先玄学对待罢，还是有几次能正常开起来的，多开开就行，之后再排查（ usb驱动需要多线程，正在进行多线程相关的代码适配，工作量比较小，明天直接干掉后应该或许大概就能开始写具体的驱动了，也许后续可以改成协程？
> 
> rust好像没有官方协程，只有await async模型，代码中executer应该就是基于await async模型实现的。又或者说把整个程序都扔到一个executer里来提高性能？ 话说还有什么代码需要写的？

看来并不能玄学对待，通过测试的情况反而用不了，看来我们还是得修一下这个bug，看了下手册，应该是控制环和事件环的TRB地址出问题了，正在排查

**Comment by dbydd** [comment]
草，问题找到了
我没写中断处理部分
正在参考https://github.com/rsta2/circle/blob/master/lib/usb/xhcidevice.cpp#L222糊一个

**Comment by 0130w** [comment]
> 草，问题找到了 我没写中断处理部分 正在参考[https://github.com/rsta2/circle/blob/master/lib/usb/xhcidevice.cpp#L222糊一个](https://github.com/rsta2/circle/blob/master/lib/usb/xhcidevice.cpp#L222%E7%B3%8A%E4%B8%80%E4%B8%AA)

难绷，但我试了一下axhal的那个关闭中断还是有那个error，这个让host_system_error位变的中断是啥？
中断处理是不是可以直接调axhal::irq::register_handler来搞

**Comment by 0130w** [comment]
他这个是不是那个中断号为30的中断要是在run之前来了就会挂（

**Comment by dbydd** [comment]
这玩意走的是pcie的msi-x中断，和axhal里面那个可能不是一码事？发件人: ***@***.*** ***@***.***> 代表 Kato0130 ***@***.***>发送时间: 2024年3月4日星期一 00:48收件人: arceos_experiment ***@***.***>抄送: 1992003927 ***@***.***>; assign ***@***.***>主题: Re: [arceos-usb/arceos_experiment] control transfer/系统相关结构完善(中断，交换内存，指令环...) (Issue #9)

草，问题找到了 我没写中断处理部分 正在参考https://github.com/rsta2/circle/blob/master/lib/usb/xhcidevice.cpp#L222糊一个

难绷，但我试了一下axhal的那个关闭中断还是有那个error，这个让host_system_error位变的中断是啥？
中断处理是不是可以直接调axhal::irq::register_handler来搞

**Comment by dbydd** [comment]
> > 草，问题找到了 我没写中断处理部分 正在参考[https://github.com/rsta2/circle/blob/master/lib/usb/xhcidevice.cpp#L222糊一个](https://github.com/rsta2/circle/blob/master/lib/usb/xhcidevice.cpp#L222%E7%B3%8A%E4%B8%80%E4%B8%AA)
> 
> 难绷，但我试了一下axhal的那个关闭中断还是有那个error，这个让host_system_error位变的中断是啥？
> 中断处理是不是可以直接调axhal::irq::register_handler来搞

可以看下xhci的文档，导致host system error的原因可能是控制环和事件环等应该塞地址的地方塞进去的数据不对，也可能是其他原因，我怀疑多半是中断向量没注册导致的...

**Comment by 0130w** [comment]
大概按照circle写了一下，今晚检查一下，应该要debug查查（

**Comment by dbydd** [comment]
修好咯,最终还是全部重写了一遍,接下来写usbport部分的代码

**Comment by 0130w** [comment]
冲刺冲刺，给我也来点（

**Comment by 0130w** [comment]
那我这两天试一下，就libusb的那个，然后和libusbi链接一下试试

**Comment by xxczxp** [comment]
还有什么要做的吗？
